name: Code check and Publish

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

jobs:
  quality:
    runs-on: ubuntu-latest
    name: Quality Check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: "latest"
      - name : fix styling
        run : ormat:fix
      - name: Run Biome
        run: biome ci .

  publish:
    needs: quality
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        id: pnpm-install
        with:
          run_install: false
          version : 9

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: publish package
        run: pnpm pub:release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_TOKEN}}